version: "2.1"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run start"
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true